name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov playwright
          playwright install --with-deps

      - name: Wait for Postgres
        run: sleep 10

      - name: Run Alembic migrations on test DB
        run: alembic upgrade head

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run security checks
        run: |
          pip install bandit
          bandit -r app

  deploy:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t $DOCKER_USERNAME/final_project:latest .
          docker push $DOCKER_USERNAME/final_project:latest
