name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fastapi_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov requests playwright
          playwright install --with-deps

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@db:5432/fastapi_test_db
          TEST_DATABASE_URL: postgresql://postgres:postgres@db:5432/fastapi_test_db
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=app --cov-report=term-missing
